name: josefrichberg
favicon: null
layout_spectrum: 0.933447513030842
typography_spectrum: 0.04672551969997585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6619004285894334
  lightness: 0.9932658558245748
  saturation: 0.5808270073030144
  rhythmicContrast: 0.5625413497909904
purpose: []
